# Use postgres/example user/password credentials
services:
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 1gb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - /home/matheusco/Documents/DATA_ANALYSIS/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: integration
      POSTGRES_PASSWORD: secret_123